backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: ergolabs/ergodex_landing
  base_url: https://ergodex.io

publish_mode: editorial_workflow
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'en_update'
    label: 'English update post'
    folder: 'content/en/updates'
    path: '{{title}}/index'
    slug: 'index'
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - label: 'Author Photo'
        name: 'authorPhoto'
        widget: 'image'
      - { label: 'Blog Photo', name: 'blogPhoto', widget: 'image' }
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ['Roadmap', 'Partnerships']
        default: []
      - { label: 'Body', name: 'body', widget: 'markdown' }